version: "3.7"
services:
  app:
    build:
      args:
        user: uloydev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: louvrea
    container_name: louvrea-app
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - mariadb
    volumes:
      - ./:/var/www
    networks:
      - louvrea
  nginx:
    image: nginx:1.17-alpine
    container_name: louvrea-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - louvrea
  mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: louvrea
            MYSQL_USER: louvrea
            MYSQL_PASSWORD: louvrea
        networks:
            - louvrea
        restart: on-failure
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - databaseVolume:/var/lib/mysql
volumes:
    databaseVolume:
networks:
  louvrea:
    driver: bridge
